### ISSUE TITLE
Refresh button for responses in admin mode

### ISSUE THREAD

**Issue by ginolhac** [daattali/shinyforms#21]
I used `shinyforms` for a real case and people started filling it up.
It works well, I actually used the fork from @fozy81(adding the right dependency to the latest shiny) to get more input types.
In the admin mode, you can see the answers but you cannot refresh it. You need to refresh the page and log in again, which is a bit annoying.
Could we have a refresh button in the admin mode to load again the `csv` files?
Many thanks again Dean!

**Comment by daattali** [comment]
It's not ready for production use! Im graduating this month so I can't work
on it at all right now but there's a ton I want to add aba change. The
entire "view responses" experience is going to change. I'm warning you ,
the form you have might completely break in a few weeks when I make big
updates to the package... But glad to know you find it useful already! I'll
definitely have the functionality you find missing

**Comment by ginolhac** [comment]
Do not worry Dean! I know you have better things to do ;) and also I am using it for organising a workshop nothing is going to break if your package has issues.
I am actually impressed by the functionally despite the early stage.
I open the issue mostly as a reminder.
Everything fine. Good luck with the defence !

**Comment by fozy81** [comment]
Hi @ginolhac , be interesting if there's any other input types you need or ones you don't really need - add your thoughts to the issue which is open on [input types](https://github.com/daattali/shinyforms/issues/4) . I've added an 'image' type question to my fork if of interest - example in the readme. Also thinking about map inputs. 

I think few things may change. Good luck to Dean on the thesis.
