### ISSUE TITLE
Select questions randomly from list or dataframe

### ISSUE THREAD

**Issue by jonathandfitzgerald** [daattali/shinyforms#27]
I've been experimenting with `shinyforms` and it gets me really close to what I'm trying to build, which is a kind of crowdsourcing app dealing with genres in newspaper texts (i.e., I provide the text and ask is this 'news', 'information', 'ad', etc.) I have my texts and potential genres saved in a data frame, or, just as easily, a list, and I'd like to be able to show a text and questions, then after the user answers and opts to "submit another response" have a different question served. Currently I can pull random questions from the list when a new session is started, and I tried to invoke a new session with `session$reload()` and a value to generate a random number,  but refreshing the page doesn't serve a new question. Is there an easy solution for this that I might be missing? Thanks!

**Comment by daattali** [comment]
I don't fully understand what you are currently doing, but I can hypothesize that what you're describing is the result of the fact that the UI of a shiny app is cached by default, as a way to optimize apps. Try putting a `Sys.time()` in the UI, and you'll see that refreshing the page won't refresh the time. I don't think this is going to be a supported feature

**Comment by jonathandfitzgerald** [comment]
This makes sense. Thank you for your reply. I'll try to think of a workaround.
