### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by wahyudinnasrulloh** [daattali/shinyforms#39]
When i install with
`install.packages("shinyforms")`
it said not available for R version 3.6.3

then i install with `devtools::install_github("daattali/shinyforms")`
it said 

> WARNING: Rtools is required to build R packages, but is not currently installed.

**Comment by daattali** [comment]
This package is not on CRAN, it will not work with `install.packages()`.

But it should work with `remotes::install_github("daattali/shinyforms")`.

That warning is fine, it's possible the package was installed successfully, and if not then you should follow their instructions and install Rtools. In any case, this is not an issue with the package. If you're having installation issues, you will need to google for it - they're generic R problems, not specific to this package.

**Comment by Sherelle20** [comment]
i have this error when am trying to install 
I am usinf rstudio 3.6

**Downloading GitHub repo daattali/shinyforms@HEAD
sh: 1: /bin/gtar: not found
sh: 1: /bin/gtar: not found
Erreur : Failed to install 'shinyforms' from GitHub:
  erreur lors de l'exécution d'une commande
De plus : Warning messages:
1: In system(cmd) : erreur lors de l'exécution d'une commande
2: In utils::untar(tarfile, ...) :
  ‘/bin/gtar -xf '/tmp/RtmpYGRjC2/file5e307ad1421.tar.gz' -C '/tmp/RtmpYGRjC2/remotes5e30512639f1'’ returned error code 127**
