### ISSUE TITLE
Can not install shinyforms from GitHub

### ISSUE THREAD

**Issue by martinbiza** [daattali/shinyforms#40]
Hi I have troubles with installing shinyforms. I tried devtools as well as remotes but there is the same error (see below). I have correctly installed also Rtools but it does not work... Can you please help me?

Many thanks!
Martin

`> remotes::install_github("daattali/shinyforms")`
`Error: Failed to install 'unknown package' from GitHub:
  Timeout was reached: [api.github.com] Operation timed out after 10005 milliseconds with 0 out of 0 bytes received`

**Comment by daattali** [comment]
Seems like a problem with your internet/R installation. Try restarting rstudio. I just tried and it was fine. But regardless - this package is not under active development and it isn't production ready so I don't recommend using it :)

```
> remotes::install_github("daattali/shinyforms")
Downloading GitHub repo daattali/shinyforms@master
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

 1: All                                             
 2: CRAN packages only                              
 3: None                                            
 4: rlang    (a90b04b9d... -> a144ac079...) [GitHub]
 5: jsonlite (1.6.1        -> 1.7.0       ) [CRAN]  
 6: Rcpp     (1.0.3        -> 1.0.5       ) [CRAN]  
 7: later    (1.0.0        -> 1.1.0.1     ) [CRAN]  
 8: promises (1.1.0        -> 1.1.1       ) [CRAN]  
 9: httpuv   (1.5.2        -> 1.5.4       ) [CRAN]  
10: glue     (1.3.2        -> 1.4.1       ) [CRAN]  

Enter one or more numbers, or an empty line to skip updates:
3
√  checking for file 'C:\Users\D\AppData\Local\Temp\RtmpQ7LcFb\remotes4608664c4adf\daattali-shinyforms-8b89e70/DESCRIPTION' (523ms)
-  preparing 'shinyforms':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'shinyforms_0.0.0.9000.tar.gz'
   
Installing package into ‘C:/Users/D/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'shinyforms' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'shinyforms'
    finding HTML links ... done
    createFormApp                           html  
    formServer                              html  
    formUI                                  html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (shinyforms)
```

**Comment by martinbiza** [comment]
Thank you for your quick feedback, Dean :). Have a nice day, Martin-------- Původní zpráva --------Od: Dean Attali <notifications@github.com>Datum: čt 6. srp 2020 17:12Komu: daattali/shinyforms <shinyforms@noreply.github.com>Kopie: martinbiza <martin.biza@atlas.cz>, Author <author@noreply.github.com>Předmět: Re: [daattali/shinyforms] Can not install shinyforms from GitHub (#40)

Seems like a problem with your internet/R installation. Try restarting rstudio. I just tried and it was fine. But regardless - this package is not under active development and it isn't production ready so I don't recommend using it :)

> remotes::install_github("daattali/shinyforms")

Downloading GitHub repo daattali/shinyforms@master

These packages have more recent versions available.

It is recommended to update all of them.

Which would you like to update?



 1: All                                             

 2: CRAN packages only                              

 3: None                                            

 4: rlang    (a90b04b9d... -> a144ac079...) [GitHub]

 5: jsonlite (1.6.1        -> 1.7.0       ) [CRAN]  

 6: Rcpp     (1.0.3        -> 1.0.5       ) [CRAN]  

 7: later    (1.0.0        -> 1.1.0.1     ) [CRAN]  

 8: promises (1.1.0        -> 1.1.1       ) [CRAN]  

 9: httpuv   (1.5.2        -> 1.5.4       ) [CRAN]  

10: glue     (1.3.2        -> 1.4.1       ) [CRAN]  



Enter one or more numbers, or an empty line to skip updates:

3

√  checking for file 'C:\Users\D\AppData\Local\Temp\RtmpQ7LcFb\remotes4608664c4adf\daattali-shinyforms-8b89e70/DESCRIPTION' (523ms)

-  preparing 'shinyforms':

√  checking DESCRIPTION meta-information ... 

-  checking for LF line-endings in source and make files and shell scripts

-  checking for empty or unneeded directories

-  building 'shinyforms_0.0.0.9000.tar.gz'

   

Installing package into ‘C:/Users/D/Documents/R/win-library/3.6’

(as ‘lib’ is unspecified)

* installing *source* package 'shinyforms' ...

** using staged installation

** R

** byte-compile and prepare package for lazy loading

** help

*** installing help indices

  converting help for package 'shinyforms'

    finding HTML links ... done

    createFormApp                           html  

    formServer                              html  

    formUI                                  html  

** building package indices

** testing if installed package can be loaded from temporary location

*** arch - i386

*** arch - x64

** testing if installed package can be loaded from final location

*** arch - i386

*** arch - x64

** testing if installed package keeps a record of temporary installation path

* DONE (shinyforms)
